"""
make_charts.py
===============
ITU AI Readiness Hackathon (KSA) — Fintech track — Team Voxel
Visual illustrations for Step 3 (Pre-processor), and the growth-tier binning
of the 16 sectors.

WHAT EACH CHART IS FOR
----------------------
1. All sectors indexed, log scale, with the eight persistently slow sectors
   highlighted as a group. Shows the spread the national average hides.
2. Sectors ranked by Dec-2023 index, with the tier cuts drawn and located in
   the two largest gaps in the distribution.
3. National e-commerce trend with the lockdown window shaded — evidence that
   the covid_period flag built at the Collector marks a real regime.
4. Distribution of the 16 final indices with the IQR fences drawn. This is the
   chart that shows the outlier test did NOT flag the slowest sector, which is
   a result we report rather than omit.
5. The sorted distribution with the gaps between consecutive sectors annotated,
   so the tier cuts can be seen to sit in real discontinuities rather than at
   round numbers chosen for convenience.

Charts 2, 4 and 5 need only sector_growth_tiers.csv.
Charts 1 and 3 need the full Step 3 matrices.

INPUTS  (this folder):
  sector_matrix_indexed.csv   sectors x months, Jan 2019 = 100   [charts 1]
  preprocessed_wide.csv       merged monthly data, covid_period  [chart 3]
  sector_growth_tiers.csv     Sector, Index_Dec2023, Tier        [charts 2,4,5]
                              (regenerated by this script if the matrix exists)
OUTPUTS (./output/)
"""

import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

IN_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(IN_DIR, "output")
os.makedirs(OUT_DIR, exist_ok=True)

plt.rcParams["font.family"] = "DejaVu Sans"
plt.rcParams["figure.dpi"] = 150

SLOW = "#d62728"
MODERATE = "#ff9f1c"
RAPID = "#2a9d8f"
GREY = "#c4c4c4"
ACCENT = "#1f77b4"
INK = "#1B1B1B"

# Tier cuts. These are manual choices, and §5 of this script draws the
# evidence for them: both sit inside the two largest gaps in the observed
# distribution rather than at round numbers picked for convenience.
CUT_SLOW = 450
CUT_RAPID = 900


def bin_growth_tier(v: float) -> str:
    if v < CUT_SLOW:
        return "Slow adopters"
    if v < CUT_RAPID:
        return "Moderate adopters"
    return "Rapid adopters"


TIER_COLORS = {"Slow adopters": SLOW, "Moderate adopters": MODERATE,
               "Rapid adopters": RAPID}


# ---------------------------------------------------------------------
# 1. All sectors, log scale, slow group highlighted
# ---------------------------------------------------------------------
def chart1_lines(indexed, tiers):
    """Log scale, and the SLOW GROUP highlighted rather than one sector.

    The original version highlighted Jewelry alone and labelled it 'the
    laggard'. That framing asserts a uniqueness the analysis does not
    support: eight sectors sat in the bottom tier every year, and Jewelry
    is the clearest case rather than an isolated one. Highlighting the
    group is both more accurate and a stronger visual argument.

    Log scale because Miscellaneous ends near 2280 and Jewelry near 145.
    On a linear axis the top sector sets the range and everything below
    500 is compressed into an unreadable band at the bottom.
    """
    mcols = [c for c in indexed.columns if c != "Sector"]
    slow = set(tiers.loc[tiers["Tier"] == "Slow adopters", "Sector"])

    fig, ax = plt.subplots(figsize=(12, 6.5))
    for _, row in indexed.iterrows():
        if row["Sector"] in slow:
            continue
        ax.plot(mcols, row[mcols].astype(float).values, color=GREY, lw=1.1, alpha=0.9)
    for _, row in indexed.iterrows():
        if row["Sector"] not in slow:
            continue
        lw = 2.6 if row["Sector"] == "Jewelry" else 1.5
        a = 1.0 if row["Sector"] == "Jewelry" else 0.75
        ax.plot(mcols, row[mcols].astype(float).values, color=SLOW, lw=lw, alpha=a)

    ax.set_yscale("log")
    ax.axhline(100, color="black", lw=0.8, ls="--", alpha=0.5)
    ax.set_xticks(mcols[::6])
    ax.set_xticklabels(mcols[::6], rotation=45, ha="right")
    ax.set_ylabel("Index, log scale (Jan 2019 = 100)")
    ax.set_title("The national average hides a persistent split\n"
                 f"POS transaction growth by sector, Jan 2019 – Dec 2023 · "
                 f"{len(slow)} of 16 sectors in the bottom tier every year (red)",
                 fontsize=12)

    # direct labels beat a legend when the lines are the message
    end = indexed.set_index("Sector")[mcols[-1]].astype(float)
    for name in ["Miscellaneous Goods and Services", "Jewelry", "Education"]:
        if name in end.index:
            ax.annotate(name, (len(mcols) - 1, end[name]),
                        textcoords="offset points", xytext=(6, 0),
                        fontsize=8.5, va="center",
                        color=SLOW if name in slow else "#777")
    ax.margins(x=0.14)
    ax.grid(alpha=0.13, which="both")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "chart1_all_sectors_indexed.png"))
    plt.close(fig)


# ---------------------------------------------------------------------
# 2. Ranked bars, with the tier cuts visible
# ---------------------------------------------------------------------
def chart2_ranking(tiers):
    r = tiers.sort_values("Index_Dec2023")
    fig, ax = plt.subplots(figsize=(9.5, 7.2))
    ax.barh(r["Sector"], r["Index_Dec2023"], color=r["Tier"].map(TIER_COLORS))

    n = len(r)
    ax.axvline(100, color="black", lw=0.8, ls="--", alpha=0.6)
    ax.text(100, n - 0.35, "baseline", fontsize=7.5, color="#666",
            ha="center", va="bottom")
    for cut in (CUT_SLOW, CUT_RAPID):
        ax.axvline(cut, color="#555", lw=1, ls=":", alpha=0.8)
        ax.text(cut, n - 0.35, f"cut {cut}", fontsize=7.5, color="#555",
                ha="center", va="bottom")

    for i, (_, row) in enumerate(r.iterrows()):
        ax.text(row["Index_Dec2023"] + 30, i, f"{row['Index_Dec2023']:.0f}",
                va="center", fontsize=8, color="#555")

    ax.set_xlabel("Index, Dec 2023 (Jan 2019 = 100)")
    ax.set_title("Sectors ranked by digital-payment growth\n"
                 "Tier cuts sit in real discontinuities, not at convenient "
                 "round numbers — see chart 5",
                 fontsize=12)
    ax.set_xlim(0, r["Index_Dec2023"].max() * 1.14)
    ax.set_ylim(-0.7, n - 0.05)
    handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in TIER_COLORS.values()]
    ax.legend(handles, TIER_COLORS.keys(), loc="lower right", fontsize=9)
    ax.grid(alpha=0.13, axis="x")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "chart2_growth_ranking.png"))
    plt.close(fig)


# ---------------------------------------------------------------------
# 3. E-commerce trend with the lockdown window
# ---------------------------------------------------------------------
def chart3_covid(wide):
    """Axis in millions rather than matplotlib's 1e7 offset, and the two
    values that justify the covid_period flag annotated directly."""
    col = "E-Commerce (Mada) - Number of Transactions"
    y = wide[col].astype(float) / 1e6

    fig, ax = plt.subplots(figsize=(12, 5.2))
    ax.plot(wide["Date"], y, color=ACCENT, lw=2.2)

    cov = wide.loc[wide["covid_period"], "Date"]
    if len(cov):
        ax.axvspan(cov.iloc[0], cov.iloc[-1], color=SLOW, alpha=0.13,
                   label="Saudi lockdown window (Mar–Jun 2020)")

    for d in ("2020-02", "2020-05"):
        m = wide["Date"].astype(str).str.startswith(d)
        if m.any():
            v = float(y[m].iloc[0])
            ax.annotate(f"{v:.1f}M", (wide.loc[m, 'Date'].iloc[0], v),
                        textcoords="offset points", xytext=(0, 12),
                        ha="center", fontsize=9, fontweight="bold", color=INK)
            ax.scatter([wide.loc[m, "Date"].iloc[0]], [v], color=INK, s=28, zorder=5)

    ax.set_xticks(wide["Date"][::6])
    ax.set_xticklabels(wide["Date"][::6], rotation=45, ha="right")
    ax.set_ylabel("E-commerce transactions, millions (Mada cards)")
    ax.set_title("The lockdown flag marks a real regime, not a label\n"
                 "National e-commerce via Mada, with the tagged window shaded",
                 fontsize=12)
    ax.legend(loc="upper left", fontsize=9)
    ax.grid(alpha=0.13)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "chart3_ecommerce_covid_spike.png"))
    plt.close(fig)


# ---------------------------------------------------------------------
# 4. IQR fences — the outlier test that did not confirm what we expected
# ---------------------------------------------------------------------
def chart4_iqr(tiers):
    """Draws the result we report rather than the one we hoped for.

    Jewelry is clearly the lowest sector, but with 16 observations the
    1.5xIQR fences are wide enough that it is not formally flagged. The
    test flags the opposite extreme instead. Showing this makes the
    honest-reporting claim in the write-up something a reader can check
    rather than something they have to accept.
    """
    v = tiers["Index_Dec2023"]
    q1, q3 = v.quantile(0.25), v.quantile(0.75)
    iqr = q3 - q1
    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr

    fig, ax = plt.subplots(figsize=(11, 4.6))
    ax.axvspan(max(lo, 0), hi, color="#eef3f7", zorder=0)
    bp = ax.boxplot(v, vert=False, widths=0.42, patch_artist=True,
                    medianprops=dict(color=INK, lw=1.6),
                    boxprops=dict(facecolor="#dce6ee", edgecolor="#7a8b99"),
                    whiskerprops=dict(color="#7a8b99"),
                    capprops=dict(color="#7a8b99"),
                    flierprops=dict(marker="o", markerfacecolor=RAPID,
                                    markeredgecolor=RAPID, markersize=9))
    jitter = np.random.default_rng(7).normal(0, 0.055, len(v))
    ax.scatter(v, 1 + jitter, s=44, color=SLOW, alpha=0.55, zorder=4,
               edgecolors="white", linewidths=0.6)

    if hi < v.max():
        ax.axvline(hi, color=RAPID, ls="--", lw=1.3)
        ax.annotate(f"upper fence {hi:.0f}\nMiscellaneous flagged", (hi, 1.33),
                    textcoords="offset points", xytext=(8, 0), fontsize=8.5,
                    color=RAPID, va="center")
    jew = v.min()
    ax.scatter([jew], [1], s=95, facecolors="none", edgecolors=SLOW,
               linewidths=2, zorder=6)
    ax.annotate(f"Jewelry, {jew:.0f}\nlowest of the 16, and still\n"
                f"{jew - lo:.0f} points inside the lower fence",
                xy=(jew, 1), xytext=(jew + 210, 1.42),
                fontsize=8.5, color=SLOW, va="center",
                arrowprops=dict(arrowstyle="->", color=SLOW, lw=1.2,
                                connectionstyle="arc3,rad=-0.25"))
    if lo < 0:
        ax.annotate(f"Lower fence sits at {lo:.0f} — off the scale, and a negative\n"
                    f"index is impossible. With n=16 the fences are simply too\n"
                    f"wide to flag anything on the low side.",
                    xy=(0.012, 0.06), xycoords="axes fraction",
                    fontsize=8.5, color="#666", va="bottom")

    ax.set_yticks([])
    ax.set_xlabel("Index, Dec 2023 (Jan 2019 = 100)")
    ax.set_title("The outlier test did not confirm what we expected, and we report that\n"
                 f"1.5×IQR on 16 sectors: fences at {lo:.0f} and {hi:.0f}. "
                 "The slowest sector is not flagged; the fastest is",
                 fontsize=12)
    ax.grid(alpha=0.13, axis="x")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "chart4_iqr_fences.png"))
    plt.close(fig)
    return lo, hi


# ---------------------------------------------------------------------
# 5. Where the tier cuts came from
# ---------------------------------------------------------------------
def chart5_gaps(tiers):
    """A tier boundary at a round number invites the question of whether it was
    chosen to produce a convenient answer. The honest defence is to show the
    gaps and let the reader judge, including where the answer is partial.

    Both cuts land inside genuine discontinuities — the 900 cut in the second
    largest gap in the distribution, the 450 cut in the third — rather than
    slicing through a dense run of sectors. The single largest gap sits between
    the two fastest sectors, above both cuts, so it is not a candidate boundary.
    """
    s = tiers.sort_values("Index_Dec2023").reset_index(drop=True)
    vals = s["Index_Dec2023"].values
    gaps = np.diff(vals)
    rank = {i: r + 1 for r, i in enumerate(np.argsort(gaps)[::-1])}
    contains = {}
    for i in range(len(gaps)):
        for cut in (CUT_SLOW, CUT_RAPID):
            if vals[i] < cut < vals[i + 1]:
                contains[i] = cut

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.scatter(vals, np.zeros(len(vals)), s=75, color=s["Tier"].map(TIER_COLORS),
               zorder=5, edgecolors="white", linewidths=0.9)
    for i, g in enumerate(gaps):
        mid = (vals[i] + vals[i + 1]) / 2
        if i in contains:
            ax.plot([vals[i], vals[i + 1]], [0, 0], color=INK, lw=4, zorder=3)
            ax.annotate(f"gap {g:.0f}\n({rank[i]}{'st' if rank[i]==1 else 'nd' if rank[i]==2 else 'rd' if rank[i]==3 else 'th'} largest)",
                        (mid, 0), textcoords="offset points", xytext=(0, 20),
                        ha="center", fontsize=9, fontweight="bold", color=INK)
        elif rank[i] == 1:
            ax.plot([vals[i], vals[i + 1]], [0, 0], color="#999", lw=3, zorder=2)
            ax.annotate(f"largest gap ({g:.0f})\nbut both sectors sit\nabove either cut",
                        (mid, 0), textcoords="offset points", xytext=(0, -52),
                        ha="center", fontsize=8, color="#888")
        else:
            ax.annotate(f"{g:.0f}", (mid, 0), textcoords="offset points",
                        xytext=(0, -18), ha="center", fontsize=7, color="#bbb")

    for cut in (CUT_SLOW, CUT_RAPID):
        ax.axvline(cut, color="#555", ls=":", lw=1.5)
        ax.annotate(f"cut at {cut}", (cut, 0), textcoords="offset points",
                    xytext=(0, 54), ha="center", fontsize=9, color="#555")

    ax.set_yticks([])
    ax.set_ylim(-0.85, 0.85)
    ax.set_xlabel("Index, Dec 2023 (Jan 2019 = 100) — each dot is one sector")
    ax.set_title("The tier cuts are choices, so here is the evidence for them\n"
                 "Both fall inside real discontinuities rather than slicing "
                 "through a dense run of sectors",
                 fontsize=12)
    ax.grid(alpha=0.13, axis="x")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT_DIR, "chart5_tier_cut_justification.png"))
    plt.close(fig)
    return [(f"cut {c}: gap {gaps[i]:.0f} ({vals[i]:.0f}->{vals[i+1]:.0f}), "
             f"rank {rank[i]} of {len(gaps)}") for i, c in contains.items()]


def main():
    tiers_path = os.path.join(IN_DIR, "sector_growth_tiers.csv")
    idx_path = os.path.join(IN_DIR, "sector_matrix_indexed.csv")
    wide_path = os.path.join(IN_DIR, "preprocessed_wide.csv")

    if os.path.exists(idx_path):
        indexed = pd.read_csv(idx_path)
        last = indexed.columns[-1]
        tiers = indexed[["Sector", last]].copy()
        tiers.columns = ["Sector", "Index_Dec2023"]
        tiers["Tier"] = tiers["Index_Dec2023"].apply(bin_growth_tier)
        tiers.sort_values("Index_Dec2023", ascending=False).to_csv(
            os.path.join(OUT_DIR, "sector_growth_tiers.csv"), index=False)
        chart1_lines(indexed, tiers)
        print("  chart1_all_sectors_indexed.png")
    elif os.path.exists(tiers_path):
        tiers = pd.read_csv(tiers_path)
        print("  chart1 SKIPPED — sector_matrix_indexed.csv not found")
    else:
        raise FileNotFoundError(
            "Need sector_matrix_indexed.csv or sector_growth_tiers.csv in this folder.")

    chart2_ranking(tiers);  print("  chart2_growth_ranking.png")

    if os.path.exists(wide_path):
        chart3_covid(pd.read_csv(wide_path)); print("  chart3_ecommerce_covid_spike.png")
    else:
        print("  chart3 SKIPPED — preprocessed_wide.csv not found")

    lo, hi = chart4_iqr(tiers);  print("  chart4_iqr_fences.png")
    cuts = chart5_gaps(tiers);   print("  chart5_tier_cut_justification.png")

    print(f"\nIQR fences: [{lo:.0f}, {hi:.0f}]")
    print(f"Slowest sector {tiers['Index_Dec2023'].min():.0f} — "
          f"{'flagged' if tiers['Index_Dec2023'].min() < lo else 'NOT flagged'}")
    for line in cuts:
        print("  " + line)
    print(f"Tier cuts at {CUT_SLOW} and {CUT_RAPID}")


if __name__ == "__main__":
    main()
